# Create Kind cluster with ingress 

# Control plane node
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: cloudforge
nodes:
- role: control-plane 

# Worker node 1 - Nginx Ingress Controller
- role: worker
  labels: 
    node-type: "ingress"
    component: "networking"
    ingress-ready: true
  extraPortMappings:
  - containerPort: 80
    hostPort: 80
    protocol: TCP
  - containerPort: 443
    protocol: TCP
    hostPort: 443

# Worker node 2 - Kubernetes Dashboard
- role: worker
  labels:
    node-type: "general"
    component: "management"

# Worker node 3 - MinIO Object Storage
- role: worker
  labels:
    node-type: "storage"
    component: "data" 

# Worker node 4 - Redis 
- role: worker
  labels:
    node-type: "cache"
    component: redis

# Worker node 5 - PostgreSQL
- role: worker
  labels:
    node-type: "database"
    component: postgresql

# Worker node 6 - RabbitMQ
- role: worker
  labels: 
    node-type: "messaging"
    component: rabbitmq

# Worker node 7 - Prometheus + Grafana
- role: worker
  labels:
    node-type: "monitoring"
    component: observability