nodeSelector:
   node-type: storage

mode: standalone 

service: 
  type: ClusterIP
  port: 9000
  nodePort: 30900
consoleService: 
  type: ClusterIP
  port: 9001
  nodePort: 30901
auth:
  existingSecretUserKey: "root-user"
  existingSecret: "minio-secret"
  existingSecretPasswordKey: "root-password"

persistence:
  enabled: true
  storageClass: "standard"
  size: "10Gi"

resources: 
  requests: 
    cpu: "250m"
    memory: "256Mi"
  limits:
    cpu: "500m"
    memory: "512Mi"

metrics:
  serviceMonitor:
    enabled: true
    namespace: "monitoring"
    interval: "30s"
    additionalLabels:
      release: "prometheus"

# Disabled for now due to networking issues
ingress: 
  enabled: false
  #enabled: true
  #ingressClassName: nginx
  #hostname: minio.cloudforge.local

consoleIngress:
  enabled: false