---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: minio-secret
  namespace: storage
spec:
  encryptedData:
    root-password: AgCxVHWBsF0ZVknStJO99iLx+XJgvk8ymnhAHOuXQiZlXLyWYFzWn+yVkwV1lJOK9H9V3Mvi+YLrwrV7/4xF9iiOUTl+vRi7v9H17MNbFJhyX/uChWQzmqKHz08sbCj13OayzeZ4SxSaUTtYhoNow0QxH2HZlWvHY2FMDRtpoR/3xeUqXWMP1rKnxZNqt7MQrY642RPpFKSDhbc0QnDNnFfLYiHv9g6Vr4TGS2MO7pJEWBByOZNJ+lECCFZij0dFH74js5rKmUw07Yd0iGOD576/lL8fVGEoQPt2JPM71NzWNV5yhD2Gl6Ho9IGFQvqKdZIuag+Hte4b4OtzELL1BNb4WLGLmdiytFUbIlPe0bh57G5HesMpps2IvZXA+JlXA0FV4a3CHRdQoy5U1ny6J4Z+uliMXmPB6WG3joFJidFYjdGNo3DFpkx2LLxcrfRRAx4qTtodA+0s828M9yxGMX5NQoz8JqPzPWb3G3hOu3alToD9PtPw66auhS/6JDbi9VArf1mfpN+IHVAxW8ONSGxc6qTrJ5fMBlQGEtS5xBxY3QYXXJmmygfTBQDKpaeIcNe/uas8vduhgKMBlUDmB/UctWfcLkLrnDXotCNWMwWLXgthgD+Ul1qq4xS/EKCki6zgUgC5dWXHC0Kjs6yHmLEYCki8iHgaxnJ2jpSY8fyHljecdQQ24GDFw1RyUm4dBCqZXRKLqh/lMR0KYbjjCpuGQdols9g3TvIS3n+vq8H9/eneHr+HtDp4EFq2Rg==
    root-user: AgBwSwBqNKZABtqX5NQRXu5Ny3EXVmxFirWUIqDOKQBPO/6fwFag/sOT03rftrW6YUXLd64UfPpsGbKHH+2ycKpHY3A+k1RPVlMXI3f99kMTaozYWDp7gR7DFH+GeTF3awN0ltwLHTBv7qt7zMAxcC+Mp46Jjjn0x7HCX06V++lG3JpRU4WKF8jcdd62cgwRpHcxLgmeahXffQFnyik8Sq+hsgnfcxx7Cs2zHGlzV3Rg/3ikRHH3z0BNZ9qHq7x/2yq6pVh3xKem//3+W2bnopTE0l/qj2f6fr7/Xu7uVFh2gjhueymxXOviMAe2+FYmqWKfr8niOfFGfhzPhBTgVNOotXCseyGncbo/y/S3coWu5MJ+0hadApTSF2wnbuxM7dJy1bmv/VE+EBVBcF5djVflY+EDPq6EsgspE9mmFOZb2ljGRCbl8aihyJDiCS9mUPsDp/TGm4j1CqCCl7YNeR4cLF7TELZ2VmQdNg9H+9JuqAoHwDBy/GgtM67ltsBWsO1yLocoNlKtzxvR3xLVLBHZN2jH7LSKTYw1wCgQ+Wa5CF6wrrmPmQ4ySEMsw4nFgu+wKM00HabNJYqBYX4uCfVKSjUusVrlvDse9Ysf0KgblJFjAxHg2ki8VdQFQ11q7W6ZJFNpI9r3owMt01+ajLQW+qnbAbGrvlzRrTAukTRXXfghXw4teVZ1I32IYzf/yglGehkn5Zasg2gJb8ERnirpiV5aAqNwpbCourxiKP/cWflHYddJIz7QYrstXw==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/managed: "true"
      creationTimestamp: null
      name: minio-secret
      namespace: storage
    type: Opaque
